export const usStates: {id: string, name: string}[] = [
    { id: "Alabama", name: "Alabama" },
    { id: "Alaska", name: "Alaska" },
    { id: "Arizona", name: "Arizona" },
    { id: "Arkansas", name: "Arkansas" },
    { id: "California", name: "California" },
    { id: "Colorado", name: "Colorado" },
    { id: "Connecticut", name: "Connecticut" },
    { id: "Delaware", name: "Delaware" },
    { id: "Florida", name: "Florida" },
    { id: "Georgia", name: "Georgia" },
    { id: "Hawaii", name: "Hawaii" },
    { id: "Idaho", name: "Idaho" },
    { id: "Illinois", name: "Illinois" },
    { id: "Indiana", name: "Indiana" },
    { id: "Iowa", name: "Iowa" },
    { id: "Kansas", name: "Kansas" },
    { id: "Kentucky", name: "Kentucky" },
    { id: "Louisiana", name: "Louisiana" },
    { id: "Maine", name: "Maine" },
    { id: "Maryland", name: "Maryland" },
    { id: "Massachusetts", name: "Massachusetts" },
    { id: "Michigan", name: "Michigan" },
    { id: "Minnesota", name: "Minnesota" },
    { id: "Mississippi", name: "Mississippi" },
    { id: "Missouri", name: "Missouri" },
    { id: "Montana", name: "Montana" },
    { id: "Nebraska", name: "Nebraska" },
    { id: "Nevada", name: "Nevada" },
    { id: "New Hampshire", name: "New Hampshire" },
    { id: "New Jersey", name: "New Jersey" },
    { id: "New Mexico", name: "New Mexico" },
    { id: "New York", name: "New York" },
    { id: "North Carolina", name: "North Carolina" },
    { id: "North Dakota", name: "North Dakota" },
    { id: "Ohio", name: "Ohio" },
    { id: "Oklahoma", name: "Oklahoma" },
    { id: "Oregon", name: "Oregon" },
    { id: "Pennsylvania", name: "Pennsylvania" },
    { id: "Rhode Island", name: "Rhode Island" },
    { id: "South Carolina", name: "South Carolina" },
    { id: "South Dakota", name: "South Dakota" },
    { id: "Tennessee", name: "Tennessee" },
    { id: "Texas", name: "Texas" },
    { id: "Utah", name: "Utah" },
    { id: "Vermont", name: "Vermont" },
    { id: "Virginia", name: "Virginia" },
    { id: "Washington", name: "Washington" },
    { id: "West Virginia", name: "West Virginia" },
    { id: "Wisconsin", name: "Wisconsin" },
    { id: "Wyoming", name: "Wyoming" },
];
export const configs = [
    'pro_features',
    'report_features',
    'pro_features_info',
    'allow_correction',
    'allow_normalize',
    'allow_normalize_new',
    'show_offline_accept_dialog',
    'transfer_to_current',
    'intermediate_worker',
    'unidentified_enabled',
    'eld_location_enabled',
    'eld_location_enabled2',
    'firmware_update_enabled',
    'app_update_enabled',
    'telegram_logging',
    'driving_speed_reset_eld',
    'odometer_reset_eld',
    'engine_reset_eld',
    'location_reset_eld',
    'gps_speed_enabled',
    'smart_switch_coordinate',
    'pt_gps_speed_enabled',
    'log_note_not_required',
    'log_edit_disabled_new',
    'google_geocode_enabled',
    'log_edit_disabled',
    'reassign',
    'check_dot',
    'allow_direct_edit',
    'allow_dispatcher_accept',
    'allow_bulk_edit',
]